version: "3"

services:

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - ./data/:/var/lib/postgresql/data/

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 443:443
      - 80:80
    depends_on:
      - django

  django:
    container_name: django
    build:
      context: .
      dockerfile: subscription_manager/Dockerfile.production
    image: django
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=subscription_manager.core.settings.production
    env_file:
      - .env
    command: gunicorn --bind :8080 subscription_manager.core.wsgi:application
    volumes:
      - .:/srv/subscription-manager/
    depends_on:
      - postgres

  celery:
    image: django

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    env_file:
      - .env
    ports:
      - 5672:5672
      - 15672:15672
