version: "3"

services:

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=$DATABASE_NAME
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
    ports:
      - $DATABASE_PORT:5432
    restart: always

  nginx:
    image: nginx
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - static_volume:/srv/static/
    ports:
      - 443:443
      - 80:80
    depends_on:
      - django
    restart: always

  django:
    build:
      context: .
      dockerfile: subscription_manager/Dockerfile.production
    environment:
      - DJANGO_SETTINGS_MODULE=subscription_manager.settings.production
    volumes:
      - .:/srv/subscription-manager/
      - static_volume:/srv/static/
    command: gunicorn --bind :8000 subscription_manager.wsgi:application
    env_file:
      - .env
    depends_on:
      - postgres
    restart: always

  celery:
    build:
      context: .
      dockerfile: subscription_manager/Dockerfile.production
    environment:
      - DJANGO_SETTINGS_MODULE=subscription_manager.settings.production
      - C_FORCE_ROOT=True
    volumes:
      - .:/srv/subscription-manager/
    command: celery -A subscription_manager worker -l info
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    restart: always

  redis:
    image: redis
    restart: always

volumes:
  static_volume: